### ISSUE TITLE
Error when trying to use very high mutation rates

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/HexSE#107]
```console
$ python3 -m hexse.run_simulation tests/fixtures/HBV.fasta tests/fixtures/100_tree.newick --config tests/fixtures/test_HBV.yaml --circular
````

When increasing increasing `global  rate` over:

```
Creating root sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laura/Projects/ovrf/hexse/run_simulation.py", line 520, in <module>
    main()
  File "/home/laura/Projects/ovrf/hexse/run_simulation.py", line 506, in main
    root_sequence = Sequence(s, orfs, kappa, global_rate, pi, mu_values, args.circular)
  File "/home/laura/Projects/ovrf/hexse/sequence_info.py", line 87, in __init__
    self.set_substitution_rates(nt)  # Get substitution rates for the nucleotide
  File "/home/laura/Projects/ovrf/hexse/sequence_info.py", line 358, in set_substitution_rates
    sub_rates[to_nt] = self.global_rate * self.pi[current_nt]
KeyError: 'A'

```

Apparently, dictionaries are empty when sequence is mutating too often.

**Comment by ArtPoon** [comment]
I ran into a different problem when setting `global_rate` to 0.5:
```
art@Wernstrom hexse % python3 -m hexse.run_simulation tests/fixtures/HBV.fasta tests/fixtures/100_tree.newick --config tests/fixtures/test_HBV.yaml --circular --outfile issue107.fa

Started at:  2022-03-03 10:12:19.928245
Categories: {'mu1': 0.15503649427447827, 'mu2': 0.36812008945507313, 'mu3': 0.7048026537983634, 'mu4': 2.0694833038716336}
Omitted orf: [[1375, 1840]] has 3 STOP codons

Creating root sequence
Simulating on Branch Clade
Simulating on Branch Clade
Simulating on Branch Clade
Simulating on Branch 36
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/art/git/hexse/hexse/run_simulation.py", line 779, in <module>
    main()
  File "/Users/art/git/hexse/hexse/run_simulation.py", line 770, in main
    simulation.get_alignment(args.outfile)
  File "/Users/art/git/hexse/hexse/simulation.py", line 279, in get_alignment
    final_tree = self.traverse_tree()
  File "/Users/art/git/hexse/hexse/simulation.py", line 271, in traverse_tree
    clade.sequence = simulation.mutate_on_branch()
  File "/Users/art/git/hexse/hexse/simulation.py", line 148, in mutate_on_branch
    mutation = self.get_substitution()
  File "/Users/art/git/hexse/hexse/simulation.py", line 80, in get_substitution
    for nt_list in possible_nts(selected_cat):  # Check if nt list is empty
  File "/Users/art/git/hexse/hexse/simulation.py", line 74, in possible_nts
    nt_list = self.sequence.event_tree['to_nt'][to_mutation]['from_nt'][from_mutation]['category'][selected_cat][selected_omega]
KeyError: None
```

**Comment by ArtPoon** [comment]
Added print statements in `simulation.py` in new branch `iss107`.  
```console
art@Wernstrom hexse % python3 -m hexse.run_simulation tests/fixtures/HBV.fasta tests/fixtures/test_tree.txt --config tests/fixtures/test_HBV.yaml --circular --outfile issue107.fa

Started at:  2022-03-03 10:28:54.296014
Categories: {'mu1': 0.15503649427447827, 'mu2': 0.36812008945507313, 'mu3': 0.7048026537983634, 'mu4': 2.0694833038716336}
Omitted orf: [[1375, 1840]] has 3 STOP codons

Creating root sequence
Simulating on Branch A
Simulating on Branch B
Simulating on Branch Clade
Simulating on Branch C
G T mu4 None
```
Those four values are `to_mutation, from_mutation, selected_cat, selected_omega`
So `selected_omega` has become `None` somehow
