### ISSUE TITLE
handling_inputs: unable to run YAML

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/HexSE#115]
```
art@Wernstrom hexse % python3 -m hexse.run_simulation tests/fixtures/HBV.fasta tests/fixtures/100_tree.newick tests/fixtures/test_HBV.yaml --outfile issue107.fa

Started at:  2022-05-19 10:34:51.347415
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/art/git/hexse/hexse/run_simulation.py", line 456, in <module>
    main()
  File "/Users/art/git/hexse/hexse/run_simulation.py", line 412, in main
    orf_locations[strand][orfs.index(orf)]['coords'].remove(orf_coord)  # Remove from coords list
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

with this YAML:
```yaml
global_rate: 0.05
kappa: 0.3

pi: 
# Note that keys for pi values HAVE to be the exact nucleotides
  A: 0.25
  T: 0.25
  G: 0.25
  C: 0.25

orfs: 
  2849,3182:
    omega_classes: 3
    omega_shape: 1.5
    omega_dist: gamma
  
  0,837:
    omega_classes: 4
    omega_shape: 1.7
    omega_dist: gamma
  
  3173,3182:
    omega_classes: 5
    omega_shape: 1.9
    omega_dist: gamma
  
  156,837:
    omega_classes: 6
    omega_shape: 1.2
    omega_dist: gamma
  
  1375,1840:
    omega_classes: 7
    omega_shape: 1.30
    omega_dist: gamma
  
  1815,2454:
    omega_classes: 3
    omega_shape: 1.25
    omega_dist: gamma
  
  1853,1922:
    omega_classes: 4
    omega_shape: 1.87
    omega_dist: gamma
  
  1902,2454:
    omega_classes: 5
    omega_shape: 2.5
    omega_dist: gamma


mu:
  classes: 2
  shape: 1.0
  dist: lognorm

circular: false
```

**Comment by ArtPoon** [comment]
at commit 0d94097d39ccdbb0fbd987b0e6903b5d3ce9d557
```console
art@Wernstrom hexse % python3 --version
Python 3.9.10
art@Wernstrom hexse % python3
Python 3.9.10 (main, Jan 15 2022, 11:48:15) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.20.3'
>>> 
```
