### ISSUE TITLE
Invalid orfs causing indexing errors. 

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/HexSE#116]
The following run cause and indexing error:
```console
$ python3 -m hexse.run_simulation tests/fixtures/HBV.fasta tests/fixtures/100_tree.newick tests/fixtures/test_HBV.yaml

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laura/Projects/ovrf/hexse/run_simulation.py", line 453, in <module>
    main()
  File "/home/laura/Projects/ovrf/hexse/run_simulation.py", line 441, in main
    root_sequence = Sequence(s, orfs, kappa, global_rate, pi, mu_values, circular)
  File "/home/laura/Projects/ovrf/hexse/sequence_info.py", line 133, in __init__
    self.set_substitution_rates(nt)  # Get substitution rates for the nucleotide, store omega combos in self.total_omegas
  File "/home/laura/Projects/ovrf/hexse/sequence_info.py", line 402, in set_substitution_rates
    chosen_omegas[orf_index] = omega_index
IndexError: list assignment index out of range
```
For the following `config` file:

```yaml
global_rate: 0.05
kappa: 0.3

pi: 
# Note that keys for pi values HAVE to be the exact nucleotides
  A: 0.25
  T: 0.25
  G: 0.25
  C: 0.25

orfs: 
  2849,3182:
    omega_classes: 3
    omega_shape: 1.5
    omega_dist: gamma
  
  0,837:
    omega_classes: 4
    omega_shape: 1.7
    omega_dist: gamma
  
  3173,3182:
    omega_classes: 5
    omega_shape: 1.9
    omega_dist: gamma
  
  156,837:
    omega_classes: 6
    omega_shape: 1.2
    omega_dist: gamma
  
  1375,1840:
    omega_classes: 7
    omega_shape: 1.30
    omega_dist: gamma
  
  1815,2454:
    omega_classes: 3
    omega_shape: 1.25
    omega_dist: gamma
  
  1853,1922:
    omega_classes: 4
    omega_shape: 1.87
    omega_dist: gamma
  
  1902,2454:
    omega_classes: 5
    omega_shape: 2.5
    omega_dist: gamma


mu:
  classes: 2
  shape: 1.0
  dist: lognorm

circular: false

```
It happens because when we create the `orf_map` in `settings/__init__.py`, each tuple has a number of positions equivalent to the number of orfs in the `config` file (e.g., `0, 0, 0, 0, 0, 0, 0, 1]`). However, some orfs can be detected as invalid in `run_simulation.py`:

```python
 for strand in orf_locations:
        orfs = orf_locations[strand]
        for idx, orf in enumerate(orfs):
            for orf_coord in orf['coords']:
                if strand == '-':       # Reverse strand
                    stop_count = count_internal_stop_codons(Sequence.complement(s), strand, orf_coord)
                else:                   # Forward strand
                    stop_count = count_internal_stop_codons(s, strand, orf_coord)

                # CDS has more than one stop codon (the final one)
                if stop_count > 1:
                    orf_locations[strand][idx]['coords'].remove(orf_coord)  # Remove from coords list
                    print(f"Omitted orf: {orf_coord} in {orf['coords']}, has {stop_count} STOP codons")

        # Coordinates are empty due to removal for introduction of early STOPS codons
        orf_locations[strand][:] = [orf for orf in orfs if orf['coords']]
    
    # Since ORFs are valid, sort the ORFs by reading frame
    orfs = sort_orfs(orf_locations)
    logging.info("Valid orfs: {}".format(orfs))

    # Check if sequence is valid
    if not valid_sequence(s):
        print("Invalid sequence: {}".format(s))
        logging.error("Invalid sequence: {}".format(s))
        sys.exit(0)
``` 
When invalid orfs are removed (`Omitted orf: [1375, 1840] in, has 3 STOP codons`), the number of positions in the tuple becomes larger than the number of actual `orfs` in `sequence`.

**Comment by horaciobam** [comment]
It worked!
